version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: resume-analyzer-db
    restart: always
    environment:
      POSTGRES_DB: resume_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sachin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./resume-analyzer-backend
      dockerfile: Dockerfile
    container_name: resume-analyzer-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
    depends_on:
      - db

volumes:
  pgdata:
